### ISSUE TITLE
how to add mimic joint?

### ISSUE THREAD

**Issue by majiqiang** [a-price/schunkPG70_description#1]
hello, i want to know how to add mimic joint.
only this sentence  "<mimic joint="gripper_a" />"  ?
please help me!

**Comment by a-price** [comment]
The mimic joint for this robot is implemented here:
https://github.com/a-price/schunk_pg70_description/blob/27bb4e48c6fb67851c3c40deaa736e27d233ec38/robots/schunk_pg70_description.URDF#L153

If you have questions about general URDF features, I'd recommend consulting the documentation on the ROS Wiki. Info on mimic joints can be found here:
http://wiki.ros.org/urdf/XML/joint#Elements
